import { useState } from 'react'
import { Link } from 'react-router-dom'

import { teacherReviewData } from '../data/teacherReview'
import { ROUTE_PATH } from '../routes/paths'
import { buildTimeOfDayGreeting } from '../utils/greeting'
import styles from './TeacherReviewPage.module.css'

type GradeDecision = 'agree' | 'disagree' | null

export function TeacherReviewPage() {
  const { instructorName, summaryTitle, summaryBody, suggestedGrade } = teacherReviewData
  const [decision, setDecision] = useState<GradeDecision>(null)
  const [disagreeNotes, setDisagreeNotes] = useState('')
  const greeting = buildTimeOfDayGreeting(new Date(), instructorName)

  return (
    <main className={styles.page}>
      <p className={styles.greeting}>{greeting}</p>
      <p className={styles.status}>We&apos;ve finished our initial grading for this session.</p>

      <div className={styles.grid}>
        <section className={styles.card} aria-labelledby="evidence-summary-title">
          <h2 id="evidence-summary-title">{summaryTitle}</h2>
          <p>{summaryBody}</p>
        </section>

        <aside className={styles.card} aria-labelledby="suggested-grade-title">
          <h2 id="suggested-grade-title">Suggested Grade</h2>
          <p className={styles.gradeValue}>{suggestedGrade}</p>
          <p className={styles.gradeHint}>
            This comes from the evidence packet generated by the LLM pipeline.
          </p>
        </aside>
      </div>

      <fieldset className={styles.decision} data-selected={decision ?? undefined}>
        <legend>Review Decision</legend>
        <div className={styles.options}>
          <label className={styles.option} data-selected={decision === 'agree' || undefined}>
            <input
              type="radio"
              name="grade-decision"
              value="agree"
              checked={decision === 'agree'}
              onChange={() => setDecision('agree')}
            />
            Agree with Suggested Grade
          </label>
          <label className={styles.option} data-selected={decision === 'disagree' || undefined}>
            <input
              type="radio"
              name="grade-decision"
              value="disagree"
              checked={decision === 'disagree'}
              onChange={() => setDecision('disagree')}
            />
            Override Suggested Grade
          </label>
        </div>
      </fieldset>

      {decision === 'disagree' ? (
        <section className={styles.disagreeNotes} aria-live="polite">
          <label htmlFor="disagree-notes">What Did You Disagree With?</label>
          <textarea
            id="disagree-notes"
            name="disagree-notes"
            value={disagreeNotes}
            onChange={(event) => setDisagreeNotes(event.target.value)}
            placeholder="Write the point(s) you disagreed with..."
            rows={5}
          />
        </section>
      ) : null}

      <footer className={styles.footer}>
        <Link className={styles.primaryButton} to={ROUTE_PATH.TEACHER_FEEDBACK}>
          Continue to Feedback
        </Link>
      </footer>
    </main>
  )
}
